CREATE DATABASE simcity CHARACTER SET = utf8;
USE simcity;

/*分类*/
CREATE TABLE category
(category_id TINYINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY, 
category_name VARCHAR(15),
created_at TIMESTAMP NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
)ENGINE = InnoDB CHARACTER SET = utf8;

/*材料*/
CREATE TABLE material
(material_id TINYINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY, 
category_id TINYINT UNSIGNED NOT NULL,
material_name VARCHAR(20), 
lead_time SMALLINT UNSIGNED NOT NULL DEFAULT 0,
time_unit VARCHAR(3) NOT NULL DEFAULT 'min',
lowest_export_price DECIMAL(15,2) DEFAULT 0.00,
hightest_export_price DECIMAL(15,2) DEFAULT 0.00,
lowest_import_price DECIMAL(15,2) DEFAULT 0.00,
created_at TIMESTAMP NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
FOREIGN KEY (category_id)
	REFERENCES category(category_id)
)ENGINE = InnoDB CHARACTER SET = utf8;

/*边*/
CREATE TABLE material_edge
(edge_id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY, 
fromNode TINYINT UNSIGNED NOT NULL,
toNode TINYINT UNSIGNED NOT NULL,
volume TINYINT UNSIGNED DEFAULT 0,
created_at TIMESTAMP NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
)ENGINE = InnoDB CHARACTER SET = utf8;

ALTER TABLE material_edge ADD FOREIGN KEY (fromNode) REFERENCES material(material_id);
ALTER TABLE material_edge ADD FOREIGN KEY (toNode) REFERENCES material(material_id);

/*仓库*/
CREATE TABLE warehouse
(warehouse_id TINYINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY, 
facility_upgrade VARCHAR(10),
volume TINYINT UNSIGNED DEFAULT 0,
is_upgrade TINYINT(1) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
)ENGINE = InnoDB CHARACTER SET = utf8;
